# Generated by Django 2.1.5 on 2019-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='upload_location', verbose_name='Аватар'),
        ),
    ]
