# Generated by Django 2.1.5 on 2019-01-17 12:29

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190117_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, default='def-avatar.png', height_field='height_field', null=True, upload_to=post.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], default='', max_length=7, verbose_name='Пол'),
        ),
    ]
