# Generated by Django 2.1.5 on 2019-01-17 12:43

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190117_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, default='media/def-avatar.png', height_field='height_field', null=True, upload_to=post.models.upload_location, width_field='width_field'),
        ),
    ]
