# Generated by Django 2.1.5 on 2019-01-17 14:35

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190117_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='contacts',
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=post.models.upload_location, width_field='width_field'),
        ),
    ]
