# Generated by Django 2.1.5 on 2019-01-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190117_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='moderation',
        ),
    ]
